#!/bin/python3

#
#  Copyright (c) 2021.  SandboxZilla
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy of this
#  software and associated documentation files (the "Software"), to deal in the Software
#  without restriction, including without limitation the rights to use, copy, modify,
#  merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
#  permit persons to whom the Software is furnished to do so.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
#  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
#  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#

KEYS = {
    "a": {"shifted": False, "code": "KeyA"},
    "b": {"shifted": False, "code": "KeyB"},
    "c": {"shifted": False, "code": "KeyC"},
    "d": {"shifted": False, "code": "KeyD"},
    "e": {"shifted": False, "code": "KeyE"},
    "f": {"shifted": False, "code": "KeyF"},
    "g": {"shifted": False, "code": "KeyG"},
    "h": {"shifted": False, "code": "KeyH"},
    "i": {"shifted": False, "code": "KeyI"},
    "j": {"shifted": False, "code": "KeyJ"},
    "k": {"shifted": False, "code": "KeyK"},
    "l": {"shifted": False, "code": "KeyL"},
    "m": {"shifted": False, "code": "KeyM"},
    "n": {"shifted": False, "code": "KeyN"},
    "o": {"shifted": False, "code": "KeyO"},
    "p": {"shifted": False, "code": "KeyP"},
    "q": {"shifted": False, "code": "KeyQ"},
    "r": {"shifted": False, "code": "KeyR"},
    "s": {"shifted": False, "code": "KeyS"},
    "t": {"shifted": False, "code": "KeyT"},
    "u": {"shifted": False, "code": "KeyU"},
    "v": {"shifted": False, "code": "KeyV"},
    "w": {"shifted": False, "code": "KeyW"},
    "x": {"shifted": False, "code": "KeyX"},
    "y": {"shifted": False, "code": "KeyY"},
    "z": {"shifted": False, "code": "KeyZ"},
    "1": {"shifted": False, "code": "Digit1"},
    "2": {"shifted": False, "code": "Digit2"},
    "3": {"shifted": False, "code": "Digit3"},
    "4": {"shifted": False, "code": "Digit4"},
    "5": {"shifted": False, "code": "Digit5"},
    "6": {"shifted": False, "code": "Digit6"},
    "7": {"shifted": False, "code": "Digit7"},
    "8": {"shifted": False, "code": "Digit8"},
    "9": {"shifted": False, "code": "Digit9"},
    "0": {"shifted": False, "code": "Digit0"},
    "A": {"shifted": True, "code": "KeyA"},
    "B": {"shifted": True, "code": "KeyB"},
    "C": {"shifted": True, "code": "KeyC"},
    "D": {"shifted": True, "code": "KeyD"},
    "E": {"shifted": True, "code": "KeyE"},
    "F": {"shifted": True, "code": "KeyF"},
    "G": {"shifted": True, "code": "KeyG"},
    "H": {"shifted": True, "code": "KeyH"},
    "I": {"shifted": True, "code": "KeyI"},
    "J": {"shifted": True, "code": "KeyJ"},
    "K": {"shifted": True, "code": "KeyK"},
    "L": {"shifted": True, "code": "KeyL"},
    "M": {"shifted": True, "code": "KeyM"},
    "N": {"shifted": True, "code": "KeyN"},
    "O": {"shifted": True, "code": "KeyO"},
    "P": {"shifted": True, "code": "KeyP"},
    "Q": {"shifted": True, "code": "KeyQ"},
    "R": {"shifted": True, "code": "KeyR"},
    "S": {"shifted": True, "code": "KeyS"},
    "T": {"shifted": True, "code": "KeyT"},
    "U": {"shifted": True, "code": "KeyU"},
    "V": {"shifted": True, "code": "KeyV"},
    "W": {"shifted": True, "code": "KeyW"},
    "X": {"shifted": True, "code": "KeyX"},
    "Y": {"shifted": True, "code": "KeyY"},
    "Z": {"shifted": True, "code": "KeyZ"},
    "!": {"shifted": True, "code": "Digit1"},
    "@": {"shifted": True, "code": "Digit2"},
    "#": {"shifted": True, "code": "Digit3"},
    "$": {"shifted": True, "code": "Digit4"},
    "%": {"shifted": True, "code": "Digit5"},
    "^": {"shifted": True, "code": "Digit6"},
    "&": {"shifted": True, "code": "Digit7"},
    "*": {"shifted": True, "code": "Digit8"},
    "(": {"shifted": True, "code": "Digit9"},
    ")": {"shifted": True, "code": "Digit0"},
    "\n": {"shifted": False, "code": "Enter"},
    "Enter": {"shifted": False, "code": "Enter"},
    "Esc": {"shifted": False, "code": "Escape"},
    "\b": {"shifted": False, "code": "Backspace"},
    "\t": {"shifted": False, "code": "Tab"},
    "Backspace": {"shifted": False, "code": "Backspace"},
    "Tab": {"shifted": False, "code": "Tab"},
    " ": {"shifted": False, "code": "Space"},
    "-": {"shifted": False, "code": "Minus"},
    "=": {"shifted": False, "code": "Equal"},
    "[": {"shifted": False, "code": "BracketLeft"},
    "]": {"shifted": False, "code": "BracketRight"},
    "\\": {"shifted": False, "code": "Backslash"},
    ";": {"shifted": False, "code": "Semicolon"},
    "'": {"shifted": False, "code": "Quote"},
    "`": {"shifted": False, "code": "BackQuote"},
    ",": {"shifted": False, "code": "Comma"},
    ".": {"shifted": False, "code": "Period"},
    "/": {"shifted": False, "code": "Slash"},
    "{": {"shifted": True, "code": "BracketLeft"},
    "}": {"shifted": True, "code": "BracketRight"},
    "|": {"shifted": True, "code": "Backslash"},
    ":": {"shifted": True, "code": "Semicolon"},
    '"': {"shifted": True, "code": "Quote"},
    "~": {"shifted": True, "code": "BackQuote"},
    "<": {"shifted": True, "code": "Comma"},
    ">": {"shifted": True, "code": "Period"},
    "?": {"shifted": True, "code": "Slash"},
    "CapsLock": {"shifted": False, "code": "CapsLock"},
    "F1": {"shifted": False, "code": "F1"},
    "F2": {"shifted": False, "code": "F2"},
    "F3": {"shifted": False, "code": "F3"},
    "F4": {"shifted": False, "code": "F4"},
    "F5": {"shifted": False, "code": "F5"},
    "F6": {"shifted": False, "code": "F6"},
    "F7": {"shifted": False, "code": "F7"},
    "F8": {"shifted": False, "code": "F8"},
    "F9": {"shifted": False, "code": "F9"},
    "F10": {"shifted": False, "code": "F10"},
    "F11": {"shifted": False, "code": "F11"},
    "F12": {"shifted": False, "code": "F12"},
    "PrintScreen": {"shifted": False, "code": "PrintScreen"},
    "Insert": {"shifted": False, "code": "Insert"},
    "Home": {"shifted": False, "code": "Home"},
    "PageUp": {"shifted": False, "code": "PageUp"},
    "Delete": {"shifted": False, "code": "Delete"},
    "End": {"shifted": False, "code": "End"},
    "PageDown": {"shifted": False, "code": "PageDown"},
    "ArrowRight": {"shifted": False, "code": "ArrowRight"},
    "ArrowLeft": {"shifted": False, "code": "ArrowLeft"},
    "ArrowDown": {"shifted": False, "code": "ArrowDown"},
    "ArrowUp": {"shifted": False, "code": "ArrowUp"},
    "ControlLeft": {"shifted": False, "code": "ControlLeft"},
    "ShiftLeft": {"shifted": False, "code": "ShiftLeft"},
    "AltLeft": {"shifted": False, "code": "AltLeft"},
    "MetaLeft": {"shifted": False, "code": "MetaLeft"},
    "ControlRight": {"shifted": False, "code": "ControlRight"},
    "ShiftRight": {"shifted": False, "code": "ShiftRight"},
    "AltRight": {"shifted": False, "code": "AltRight"},
    "MetaRight": {"shifted": False, "code": "MetaRight"},
    "Pause": {"shifted": False, "code": "Pause"},
    "ScrollLock": {"shifted": False, "code": "ScrollLock"},
    "NumLock": {"shifted": False, "code": "NumLock"},
    "ContextMenu": {"shifted": False, "code": "ContextMenu"},
    "NumpadDivide": {"shifted": False, "code": "NumpadDivide"},
    "NumpadMultiply": {"shifted": False, "code": "NumpadMultiply"},
    "NumpadSubtract": {"shifted": False, "code": "NumpadSubtract"},
    "NumpadAdd": {"shifted": False, "code": "NumpadAdd"},
    "NumpadEnter": {"shifted": False, "code": "NumpadEnter"},
    "Numpad1": {"shifted": False, "code": "Numpad1"},
    "Numpad2": {"shifted": False, "code": "Numpad2"},
    "Numpad3": {"shifted": False, "code": "Numpad3"},
    "Numpad4": {"shifted": False, "code": "Numpad4"},
    "Numpad5": {"shifted": False, "code": "Numpad5"},
    "Numpad6": {"shifted": False, "code": "Numpad6"},
    "Numpad7": {"shifted": False, "code": "Numpad7"},
    "Numpad8": {"shifted": False, "code": "Numpad8"},
    "Numpad9": {"shifted": False, "code": "Numpad9"},
    "Numpad0": {"shifted": False, "code": "Numpad0"},
    "NumpadDecimal": {"shifted": False, "code": "NumpadDecimal"},
    "Power": {"shifted": False, "code": "Power"},
    "IntlBackslash": {"shifted": False, "code": "IntlBackslash"},
    "IntlYen": {"shifted": False, "code": "IntlYen"},
}
